spring.application.name=ai-chat

# ????????? SQLite
spring.datasource.url=jdbc:sqlite:local_chat.db
spring.datasource.driver-class-name=org.sqlite.JDBC



# always ??????? ????????????? ????? ????? ??????????? ?????? ??? ??????? ??????????
#        (????????????? ??? SQLite ? ???????? ??????????)
# never ????????????? ????? ????????? (???? ?????? ?????? ???? ???????????? ??????? ???????)
# embedded ????? ????????? ?????? ? ??? ??????, ???? ???????????? ?????????? ?? ? ?????? (????????, H2 ??? HSQL).
#          ????????? SQLite ???????? ???????? ??, ???? ????? ????? ?? ????????? ?????????????,
#          ??????? ???????? ???????????? always.
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# ???????????? Ollama ??? Qwen 2.5 Coder
spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=qwen2.5-coder:7b
spring.ai.ollama.chat.model=qwen2.5:7b
# ???????????: ????? ???? ?????? ??????????? (0.1?0.3 ???????? ??? ??????? ?????? ? ?????? ? Tools)
spring.ai.ollama.chat.temperature=0.2